FROM mysql:8.0-debian
RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "-y", "curl"]
CMD ["--default-authentication-plugin=mysql_native_password"]
COPY database-import.sh /bin/import
COPY database-setup.sql /docker-entrypoint-initdb.d/0-setup.sql
RUN ["ln", "-s", "/bin/import", "/docker-entrypoint-initdb.d/1-import.sh"]
ENV MYSQL_ALLOW_EMPTY_PASSWORD=true
