FROM node:14
RUN ["apt-get", "update", "-y"]
RUN ["apt-get", "install", "-y", "netcat"]
RUN ["npm", "install", "-g", "npm"]
RUN ["mkdir", "/storage"]
RUN ["chown", "-R", "node:node", "/storage"]
USER node
WORKDIR /app/server
COPY api-entrypoint.sh /
CMD ["/api-entrypoint.sh"]
